version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - BASE_API_URL=http://backend:8080/api/v1/recipes
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - SPOONACULAR_API_KEY=${SPOONACULAR_API_KEY}
      - SPOONACULAR_BASE_URL=${SPOONACULAR_BASE_URL}